In [12]:
import pandas as pd
import numpy as np
from pathlib import Path
import seaborn as sns
import glob
import matplotlib.pyplot as plt

In [13]:
import os
print(os.getcwd())

e:\Github\nordpool_electricity_price_prediction\data\originalData\WindDirection&Speed

In [14]:
files = glob.glob(
    "e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed/*.csv"
)

print(files)

['e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.1.2023 - 30.4.2023.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.1.2024 - 30.4.2024.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.1.2025 - 30.4.2025.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.5.2023 - 31.8.2023.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.5.2024 - 31.8.2024.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.5.2025 - 31.8.2025.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.9.2023 - 31.12.2023.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.9.2024 - 31.12.2024.csv', 'e:/Github/nordpool_electricity_price_prediction/data/originalData/WindDirection&Speed\\Oulu Vihreäsaari harbour_ 1.9.2025 - 31.12.2025.csv']

In [15]:
df_list=[]

for file in files:

    wind=pd.read_csv(file)

    df_list.append(wind)

wind_df=pd.concat(df_list)

print(wind_df.shape)

(157806, 7)

In [16]:
wind_df.info();wind_df.describe();wind_df.sample(5)

<class 'pandas.DataFrame'>
Index: 157806 entries, 0 to 17567
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Observation station      157806 non-null  str
 1   Year                     157806 non-null  int64
 2   Month                    157806 non-null  int64
 3   Day                      157806 non-null  int64
 4   Time [Local time]        157806 non-null  str
 5   Wind direction mean [°]  157806 non-null  str
 6   Wind speed mean [m/s]    157806 non-null  str
dtypes: int64(3), str(4)
memory usage: 9.6 MB

,Observation station,Year,Month,Day,Time [Local time],Wind direction mean [°],Wind speed mean [m/s]
16861,Oulu Vihreäsaari harbour,2023,8,26,02:10,118.5,2.5
15551,Oulu Vihreäsaari harbour,2023,4,19,00:50,175.4,1.4
14593,Oulu Vihreäsaari harbour,2025,12,11,08:10,35.2,3.6
14164,Oulu Vihreäsaari harbour,2023,12,8,08:40,130.2,7
14872,Oulu Vihreäsaari harbour,2023,4,14,07:40,113.1,5.3

In [17]:
wind_df.isnull().sum();

In [21]:
#convert the 'Wind speed mean [m/s]' column to numeric, and coerce any errors to NaN
wind_df['Wind speed mean [m/s]'] = pd.to_numeric(wind_df['Wind speed mean [m/s]'], errors='coerce')
wind_df['Wind direction mean [°]'] = pd.to_numeric(wind_df['Wind direction mean [°]'], errors='coerce')

#forward fill the missing values in the 'Wind speed mean [m/s]' column
wind_df['Wind speed mean [m/s]'] = wind_df['Wind speed mean [m/s]'].ffill()
#forward fill the missing values in the 'Wind direction mean [°]' column
wind_df['Wind direction mean [°]'] = wind_df['Wind direction mean [°]'].ffill()

In [22]:
wind_df.info()

<class 'pandas.DataFrame'>
Index: 157806 entries, 0 to 17567
Data columns (total 7 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Observation station      157806 non-null  str
 1   Year                     157806 non-null  int64
 2   Month                    157806 non-null  int64
 3   Day                      157806 non-null  int64
 4   Time [Local time]        157806 non-null  str
 5   Wind direction mean [°]  157806 non-null  float64
 6   Wind speed mean [m/s]    157806 non-null  float64
dtypes: float64(2), int64(3), str(2)
memory usage: 9.6 MB

In [24]:
#create a new column 'datetime_str' by concatenating the 'Year', 'Month', 'Day', and 'Time [Local time]' columns, and then convert this new column to a datetime object in a new column called 'datetime'
wind_df['datetime_str'] = wind_df['Year'].astype(str) + '-' + wind_df['Month'].astype(str) + '-' + wind_df['Day'].astype(str) + ' ' + wind_df['Time [Local time]']

#convert the 'datetime_str' column to a datetime object in a new column called 'datetime'
wind_df['datetime'] = pd.to_datetime(wind_df['datetime_str'])

In [25]:
#set the 'datetime' column as the index of the winddataframe
wind_df.set_index('datetime', inplace=True)

hourly_wind_speed = wind_df['Wind speed mean [m/s]'].resample('h').mean().reset_index()

In [26]:
wind_df.sample(5)

,Observation station,Year,Month,Day,Time [Local time],Wind direction mean [°],Wind speed mean [m/s],datetime_str
datetime,,,,,,,,
2025-06-07 02:30:00,Oulu Vihreäsaari harbour,2025,6,7,02:30,328.8,1.7,2025-6-7 02:30
2025-05-17 00:50:00,Oulu Vihreäsaari harbour,2025,5,17,00:50,347.8,1.9,2025-5-17 00:50
2024-05-12 06:10:00,Oulu Vihreäsaari harbour,2024,5,12,06:10,150.1,4.2,2024-5-12 06:10
2025-07-20 09:30:00,Oulu Vihreäsaari harbour,2025,7,20,09:30,316.2,1.6,2025-7-20 09:30
2025-12-18 19:10:00,Oulu Vihreäsaari harbour,2025,12,18,19:10,154.7,8.1,2025-12-18 19:10

In [29]:
#set 10 mins interval to hourly data
hourly_wind_speed = wind_df['Wind speed mean [m/s]'].resample('h').mean().reset_index()

#output hourly_wind_speed to a csv file
hourly_wind_speed.to_csv('../WindDirection&Speed/hourly_wind_speed.csv', index=False)