In [1]:
import pandas as pd

df = pd.read_csv('Helsinki-Vantaa airport_ 1.1.2023 - 30.6.2023.csv')

df.head()

,Observation station,Year,Month,Day,Time [Local time],Air temperature mean [°C]
0,Vantaa Helsinki-Vantaa airport,2023,1,1,00:00,4.4
1,Vantaa Helsinki-Vantaa airport,2023,1,1,00:10,4.5
2,Vantaa Helsinki-Vantaa airport,2023,1,1,00:20,4.5
3,Vantaa Helsinki-Vantaa airport,2023,1,1,00:30,4.5
4,Vantaa Helsinki-Vantaa airport,2023,1,1,00:40,4.4

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26058 entries, 0 to 26057
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Observation station        26058 non-null  str
 1   Year                       26058 non-null  int64
 2   Month                      26058 non-null  int64
 3   Day                        26058 non-null  int64
 4   Time [Local time]          26058 non-null  str
 5   Air temperature mean [°C]  26058 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 1.2 MB

In [2]:
df.describe()

          Year         Month           Day  Air temperature mean [°C]
count  26058.0  26058.000000  26058.000000               26058.000000
mean    2023.0      3.508404     15.599816                   4.538249
std        0.0      1.710173      8.735070                   8.815401
min     2023.0      1.000000      1.000000                 -17.700000
25%     2023.0      2.000000      8.000000                  -1.400000
50%     2023.0      4.000000     16.000000                   2.400000
75%     2023.0      5.000000     23.000000                  10.700000
max     2023.0      6.000000     31.000000                  29.600000