In [1]:
import pandas as pd
# import numpy as np
# from pathlib import Path
# import seaborn as sns
# import glob
# import matplotlib.pyplot as plt

In [4]:
# read data
df_price = pd.read_csv("../originalData/electricPrices/electricity_prices_helsinki.csv")
df_temp = pd.read_csv("../originalData/Temperature/Temperature_hourly_clean.csv")
df_wind = pd.read_csv("../originalData/WindDirection&Speed/hourly_wind_speed.csv")

# change the time column from string to datetime type
df_price['hour'] = pd.to_datetime(df_price['hour'])
df_temp['datetime'] = pd.to_datetime(df_temp['datetime'])
df_wind['datetime'] = pd.to_datetime(df_wind['datetime'])

In [5]:
#first merge: merge price and temp tables together
merge_1 = pd.merge(df_price, df_temp, left_on='hour', right_on='datetime', how='inner')

#second merge: merge the just-merged table with the wind table
final_df = pd.merge(merge_1, df_wind, left_on='hour', right_on='datetime', how='inner')

In [7]:
final_df.head()

,hour,price,datetime_x,Air temperature mean [°C],datetime_y,Wind speed mean [m/s]
0,2023-01-01 00:00:00,4.84,2023-01-01 00:00:00,4.433333,2023-01-01 00:00:00,8.516667
1,2023-01-01 01:00:00,2.01,2023-01-01 01:00:00,4.100000,2023-01-01 01:00:00,7.716667
2,2023-01-01 02:00:00,1.38,2023-01-01 02:00:00,3.800000,2023-01-01 02:00:00,8.150000
3,2023-01-01 03:00:00,0.09,2023-01-01 03:00:00,3.616667,2023-01-01 03:00:00,9.333333
4,2023-01-01 04:00:00,0.08,2023-01-01 04:00:00,2.516667,2023-01-01 04:00:00,11.700000

In [15]:
# delete the redundant time columns
final_df_clean = final_df.drop(columns=['datetime_x', 'datetime_y'])

# rename the 'hour' column to 'datetime' for better readability
final_df_clean = final_df_clean.rename(columns={'hour': 'datetime'})

# save the cleaned and merged dataset to a new CSV file
final_df_clean.to_csv("../convertData/finland_electricity_predict_dataset.csv", index=False)

In [18]:
final_df_clean.info()
final_df_clean.describe()

<class 'pandas.DataFrame'>
RangeIndex: 26304 entries, 0 to 26303
Data columns (total 4 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   datetime                   26304 non-null  datetime64[us]
 1   price                      26304 non-null  float64
 2   Air temperature mean [°C]  26304 non-null  float64
 3   Wind speed mean [m/s]      26304 non-null  float64
dtypes: datetime64[us](1), float64(3)
memory usage: 822.1 KB

,datetime,price,Air temperature mean [°C],Wind speed mean [m/s]
count,26304,26304.000000,26304.000000,26304.000000
mean,2024-07-02 00:04:52.335766,47.500456,6.943653,5.152399
min,2023-01-01 00:00:00,-500.000000,-25.966667,0.166667
25%,2023-10-02 00:45:00,5.237500,0.233333,3.183333
50%,2024-07-02 00:30:00,29.770000,6.133333,4.666667
75%,2025-04-02 00:15:00,72.562500,14.666667,6.600000
max,2025-12-31 23:00:00,1896.000000,29.516667,21.600000
std,NaN,62.366108,9.310275,2.739649

In [19]:
final_df_clean.head()

             datetime  price  Air temperature mean [°C]  Wind speed mean [m/s]
0 2023-01-01 00:00:00   4.84                   4.433333               8.516667
1 2023-01-01 01:00:00   2.01                   4.100000               7.716667
2 2023-01-01 02:00:00   1.38                   3.800000               8.150000
3 2023-01-01 03:00:00   0.09                   3.616667               9.333333
4 2023-01-01 04:00:00   0.08                   2.516667              11.700000

In [20]:
final_df_clean.max()

datetime                     2025-12-31 23:00:00
price                                     1896.0
Air temperature mean [°C]              29.516667
Wind speed mean [m/s]                       21.6
dtype: object

In [21]:
final_df_clean.min()

datetime                     2023-01-01 00:00:00
price                                     -500.0
Air temperature mean [°C]             -25.966667
Wind speed mean [m/s]                   0.166667
dtype: object