In [1]:
import pandas as pd
import numpy as np
from pathlib import Path
import seaborn as sns
import glob
import matplotlib.pyplot as plt

In [9]:
hour_price_df = pd.read_csv('electricity_prices_helsinki.csv')
hour_price_df

                      hour   price
0      2023-01-01 00:00:00    4.84
1      2023-01-01 01:00:00    2.01
2      2023-01-01 02:00:00    1.38
3      2023-01-01 03:00:00    0.09
4      2023-01-01 04:00:00    0.08
...                    ...     ...
26299  2025-12-31 19:00:00  152.00
26300  2025-12-31 20:00:00  140.00
26301  2025-12-31 21:00:00  131.41
26302  2025-12-31 22:00:00  129.91
26303  2025-12-31 23:00:00  115.73

[26304 rows x 2 columns]

In [ ]:
hour_price_df.info();hour_price_df.describe();hour_price_df.head()

<class 'pandas.DataFrame'>
RangeIndex: 26304 entries, 0 to 26303
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hour    26304 non-null  str
 1   price   26304 non-null  float64
dtypes: float64(1), str(1)
memory usage: 411.1 KB

              price
count  26304.000000
mean      47.500456
std       62.366108
min     -500.000000
25%        5.237500
50%       29.770000
75%       72.562500
max     1896.000000

In [ ]:
hour_price_df["hour"] = pd.to_datetime(
    hour_price_df["hour"]
)

hour_price_df.info()