In [2]:
import pandas as pd

df = pd.read_csv('electricity_prices_helsinki.csv')

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26304 entries, 0 to 26303
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   hour    26304 non-null  str
 1   price   26304 non-null  float64
dtypes: float64(1), str(1)
memory usage: 411.1 KB

In [3]:
df.describe()

              price
count  26304.000000
mean      47.500456
std       62.366108
min     -500.000000
25%        5.237500
50%       29.770000
75%       72.562500
max     1896.000000

In [4]:
df.head()

                  hour  price
0  2023-01-01 00:00:00   4.84
1  2023-01-01 01:00:00   2.01
2  2023-01-01 02:00:00   1.38
3  2023-01-01 03:00:00   0.09
4  2023-01-01 04:00:00   0.08